/*
====================================================
WORD LADDER II
LeetCode:
https://leetcode.com/problems/word-ladder-ii/
====================================================

💡 PROBLEM SUMMARY
- Given:
    beginWord
    endWord
    wordList

Goal:
✔ Find all shortest transformation sequences
  from beginWord to endWord.

Rules:
✔ Only one character can be changed at a time
✔ Every transformed word must exist in wordList
✔ Return only the shortest valid sequences

====================================================
KEY IDEA: BFS WITH COMPLETE PATH STORAGE
----------------------------------------------------
This approach stores the entire transformation
path inside the queue.

So instead of pushing a single word,
we push a full vector<string> representing
the path taken so far.

Why?
Because Word Ladder II requires:
✔ all shortest paths
✔ not just the shortest length

BFS ensures:
✔ first time we reach endWord,
  it is through the minimum number of steps

====================================================
APPROACH
----------------------------------------------------
STEP 1: Prepare lookup structure
----------------------------------------------------
Store all words in an unordered_set for
O(1) average lookup.

Use queue<vector<string>> to perform BFS,
where each queue element represents one
complete path from beginWord to current word.

----------------------------------------------------

STEP 2: BFS level-by-level traversal
----------------------------------------------------
For every path popped from queue:
✔ Take the last word of the path
✔ Generate all possible one-letter transformations
✔ If transformed word exists in set:
      create a new path
      push it into queue

This helps explore all possible shortest paths.

----------------------------------------------------

STEP 3: Handle visited words level-wise
----------------------------------------------------
A word should not be erased immediately
when seen for the first time.

Reason:
Two different paths in the same BFS level
may need to use the same next word.

So:
✔ collect words used in current level
✔ erase them only after the level changes

This preserves all shortest-path possibilities.

----------------------------------------------------

STEP 4: Store only shortest answers
----------------------------------------------------
When current path ends at endWord:

Case 1:
✔ ans is empty
   → first valid path found by BFS
   → definitely shortest

Case 2:
✔ ans already contains paths
   → insert current path only if its size
     matches ans[0].size()

This ensures only shortest sequences are stored.

====================================================
IMPORTANT CONDITIONS
----------------------------------------------------
✔ Entire path is stored in queue
✔ Words are removed level-wise, not immediately
✔ BFS guarantees minimum-length transformations
✔ Only paths with shortest size are added to ans
✔ All transformations are generated by replacing
  each character from 'a' to 'z'

====================================================
LIMITATION OF THIS APPROACH
----------------------------------------------------
✔ Logic is correct
✔ But it may cause Memory Limit Exceeded

Reason:
Storing full paths in queue for every BFS branch
can consume a lot of memory.

So although correct logically,
it is not efficient enough for LeetCode constraints.

====================================================
TIME & SPACE ANALYSIS
----------------------------------------------------
TIME COMPLEXITY:
Difficult to express tightly because the number
of generated paths depends heavily on the test case.

SPACE COMPLEXITY:
High, because complete paths are stored in queue,
which can grow very large.

====================================================
KEY TAKEAWAY
----------------------------------------------------
This is a correct BFS-based path generation method.

Main insight:
Store full paths and erase words level-wise
to capture all shortest sequences.

Main issue:
Memory usage becomes too large because BFS stores
many complete paths simultaneously.
====================================================
*/

#include<bits/stdc++.h>
using namespace std;

class Solution {
public:
    vector<vector<string>> findLadders(string beginWord, string endWord, vector<string>& wordList) {
        unordered_set<string> st(wordList.begin(), wordList.end());
        queue<vector<string>> q;
        q.push({ beginWord });
        vector<string> usedOnLevel;
        usedOnLevel.push_back(beginWord);
        int level = 0;
        vector<vector<string>> ans;
        while (!q.empty()) {
            vector<string> vec = q.front();
            q.pop();
            if (vec.size() > level) {
                level++;
                for (auto it : vec) {
                    st.erase(it);
                }
            }
            usedOnLevel.clear();
            string word = vec.back();

            if (word == endWord &&
                (ans.size() == 0 || ans[0].size() == vec.size())) {
                ans.push_back(vec);
            }

            for (int i = 0; i < word.size(); i++) {
                char og = word[i];
                for (char c = 'a'; c <= 'z'; c++) {
                    word[i] = c;
                    if (st.count(word) > 0) {
                        vec.push_back(word);
                        q.push(vec);
                        usedOnLevel.push_back(word);
                        vec.pop_back();
                    }
                }
                word[i] = og;
            }
        }

        return ans;
    }
};


//OPTIMAL APPROACH
/*
====================================================
WORD LADDER II — OPTIMAL APPROACH
LeetCode:
https://leetcode.com/problems/word-ladder-ii/
====================================================

💡 PROBLEM SUMMARY
- We need all shortest transformation sequences
  from beginWord to endWord.

Challenge:
✔ Return every shortest sequence
✔ Avoid storing every full path in BFS
  because that causes high memory usage

====================================================
KEY IDEA: BFS + DFS / BACKTRACKING
----------------------------------------------------
Instead of storing complete paths during BFS,
this approach splits the work into 2 phases:

1️⃣ BFS:
    beginWord  ----->  endWord

2️⃣ DFS Backtracking:
    endWord    ----->  beginWord

This combination is memory efficient and still
generates all shortest sequences.

====================================================
WHY THIS WORKS
----------------------------------------------------
BFS is used only to compute:
✔ the minimum level (distance) of each reachable word

So for every word, we store:
    mpp[word] = shortest step count from beginWord

After that, DFS starts from endWord and moves
backward only to words whose level is exactly
one less than the current word.

That means DFS explores only valid shortest paths.

====================================================
APPROACH
----------------------------------------------------
STEP 1: BFS from beginWord
----------------------------------------------------
Use standard Word Ladder I style BFS.

During BFS:
✔ Generate all one-letter transformations
✔ If a word exists in set:
      - push it into queue
      - assign its level = current level + 1
      - erase it from set

Map stores:
    word -> shortest distance from beginWord

This phase ensures we know the shortest path depth
for every reachable word.

----------------------------------------------------

STEP 2: Check if endWord is reachable
----------------------------------------------------
If endWord does not exist in the map,
then no valid transformation sequence exists.

Return empty answer.

----------------------------------------------------

STEP 3: DFS from endWord to beginWord
----------------------------------------------------
Start DFS from endWord.

At each step:
✔ Try all one-letter transformations
✔ Move only to a word present in map
✔ And only if:
      mpp[newWord] == mpp[currentWord] - 1

This guarantees:
✔ movement only along shortest path levels
✔ no unnecessary longer paths are explored

----------------------------------------------------

STEP 4: Build answer
----------------------------------------------------
DFS builds path in reverse:
    endWord -> ... -> beginWord

When beginWord is reached:
✔ reverse the sequence
✔ store it in answer

====================================================
IMPORTANT CONDITIONS
----------------------------------------------------
✔ BFS stores only level information, not full paths
✔ DFS reconstructs shortest paths using level map
✔ Backtracking condition:
      next word must be exactly one level smaller
✔ This avoids exploring invalid or longer paths
✔ Much more memory efficient than storing all
  paths directly in BFS queue

====================================================
TIME & SPACE ANALYSIS
----------------------------------------------------
TIME COMPLEXITY:
Depends on:
✔ number of words
✔ word length
✔ number of valid shortest sequences generated

Broadly:
- BFS explores transformations level by level
- DFS reconstructs only shortest paths

SPACE COMPLEXITY:
Lower than the first approach for BFS storage,
since full paths are not kept in queue.
Extra space is used for:
✔ map
✔ recursion stack
✔ answer storage

====================================================
KEY TAKEAWAY
----------------------------------------------------
Use BFS to compute shortest distance of each word,
then use DFS to reconstruct all shortest sequences.

This avoids the memory problem of storing
every full path during BFS and is the standard
optimized strategy for Word Ladder II.
====================================================
*/
class Solution2 {
    unordered_map<string, int> mpp;
    vector<vector<string>> ans;
    string b;
    int sz;

    void dfs(string word, vector<string>& seq) {
        if (word == b) {
            reverse(seq.begin(), seq.end());
            ans.push_back(seq);
            reverse(seq.begin(), seq.end());
            return;
        }

        int steps = mpp[word];
        for (int i = 0; i < sz; i++) {
            char og = word[i];
            for (char ch = 'a'; ch <= 'z'; ch++) {
                word[i] = ch;
                if (mpp.find(word) != mpp.end() && mpp[word] == steps - 1) {
                    seq.push_back(word);
                    dfs(word, seq);
                    seq.pop_back();
                }
            }
            word[i] = og;
        }
    }

public:
    vector<vector<string>> findLadders(string beginWord, string endWord, vector<string>& wordList) {
        unordered_set<string> st(wordList.begin(), wordList.end());
        queue<string> q;
        b = beginWord;
        q.push({ beginWord });
        mpp[beginWord] = 1;
        sz = beginWord.size();
        st.erase(beginWord);
        while (!q.empty()) {
            string word = q.front();
            int steps = mpp[word];
            q.pop();
            if (word == endWord) break;
            for (int i = 0; i < sz; i++) {
                char og = word[i];
                for (char ch = 'a'; ch <= 'z'; ch++) {
                    word[i] = ch;
                    if (st.count(word)) {
                        q.push(word);
                        st.erase(word);
                        mpp[word] = steps + 1;
                    }
                }

                word[i] = og;
            }
        }

        if (mpp.find(endWord) != mpp.end()) {
            vector<string> seq;
            seq.push_back(endWord);
            dfs(endWord, seq);
        }

        return ans;
    }
};


int main() {

    return 0;
}